import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
          <title>Chat-widget Examples</title>
      </head>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div id={"chat-widget"} data-apikey={"sk-12345ABCDE67890FGHIJ09876KLMNOPQR"} data-theme={"light"}/>
      <Script
          src="https://cdn.jsdelivr.net/gh/intraining-org/chat-widget/dist/chat-widget.js"
          strategy="afterInteractive"
      />
      {children}
      </body>
      </html>
  );
}
